project:
  type: website

website:
  title: "Sayuri Pamoda Ponnamperuma"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About Me
        file: about.qmd
      - text: Education
        file: education.qmd
      - text: Skills
        file: skills.qmd
      - text: Projects & Research
        file: projects.qmd
      - text: Volunteer & Extracurricular
        file: volunteer.qmd
      - text: Leadership & School
        file: leadership.qmd
      - text: Awards & Achievements
        file: awards.qmd
      - text: CV
        file: cv.qmd

format:
  html:
    theme: flatly
    toc: false
    css: styles.css
    html: true   

